### ISSUE TITLE
SMRF hangs on outputting variables

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#15]
In gitlab by @micahjohnson150 on Jul 7, 2017, 11:33

SMRF doesn't produce an error but hangs after the first timestep. Not sure whats going on... it just stops.

Last line:
**DEBUG:smrf.utils.queue:2017-01-29 00:00:00+00:00 Variables output from queues**

This occurs with the file attached.

[tuolx_smrfConfig.ini](/uploads/20a6a00e0c8c8170ea8abcb186164e79/tuolx_smrfConfig.ini)

**Comment by scotthavens** [comment]
In gitlab by @micahjohnson150 on Jul 7, 2017, 15:53

Note that the attached ini above is without a password for obvious security issues.

**Comment by scotthavens** [comment]
In gitlab by @micahjohnson150 on Jul 7, 2017, 16:01

Error is being caused by 
smrf/utils/queue.py, in DataQueue_Threaded.get(self, index, block=True, timeout=None)
at line 98 in the file.
Here is a chunk of code causing the problem:

```python
            elif self.timeout is None:
                while index not in self.queue.keys():
                    self.not_empty.wait()
```
Since no timeout is being specified then we enter into a while loop of not_empty.wait(). Applying some print statement I discovered wait is not being called repeatedly...only once.

The real question is what is getting stuck that the next index is not arriving.

@shavens got any clues? It looks like you overhauled this a month ago or so. Any thoughts?

**Comment by scotthavens** [comment]
In gitlab by @shavens on Jul 10, 2017, 08:38

A problem with queue are if they are full and something breaks, it will pause infinitely. One way around this is to set the timeout in the `[system]` section. The `wait()` command has some internal callbacks that will trigger the all done command to let go of the lock.

However, the real cause of the problem will be hidden up higher in the log file. What is happening is that one of the variables has an error that isn't being captured somehow. So that thread exits quietly, however all the other threads keep going and eventually pause on the `put` command as there is no place to put the data. So there should be a clue higher up in the log file or in the command line.

One way to debug this is to look at the dates for the distributed variables. Start counting backwards until one reappears that that will be the one that errored silently. We will want to fix this by doing a better job at catching the errors.

**Comment by scotthavens** [comment]
In gitlab by @micahjohnson150 on Jul 11, 2017, 09:48

@shavens When I do have a timeout of 60 seconds we get raise a heap of exceptions in random places. Kind of looks like a threading management issue.

```
Exception in thread sun_angle:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/micahjohnson/projects/micahenv/local/lib/python2.7/site-packages/smrf/envphys/radiation.py", line 518, in sunang_thread
    queue['cosz'].put([t, cosz])
  File "/home/micahjohnson/projects/micahenv/local/lib/python2.7/site-packages/smrf/utils/queue.py", line 148, in put
    raise Full
Full

Exception in thread illum_angle:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/micahjohnson/projects/micahenv/local/lib/python2.7/site-packages/smrf/envphys/radiation.py", line 624, in shade_thread
    cosz = queue['cosz'].get(t)
  File "/home/micahjohnson/projects/micahenv/local/lib/python2.7/site-packages/smrf/utils/queue.py", line 107, in get
    raise Empty
Empty

Exception in thread vapor_pressure:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/micahjohnson/projects/micahenv/local/lib/python2.7/site-packages/smrf/distribute/vapor_pressure.py", line 165, in distribute_thread
    ta = queue['air_temp'].get(t)
  File "/home/micahjohnson/projects/micahenv/local/lib/python2.7/site-packages/smrf/utils/queue.py", line 107, in get
    raise Empty
Empty

Exception in thread air_temp:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/micahjohnson/projects/micahenv/local/lib/python2.7/site-packages/smrf/distribute/air_temp.py", line 112, in distribute_thread
    queue[self.variable].put([t, self.air_temp])
  File "/home/micahjohnson/projects/micahenv/local/lib/python2.7/site-packages/smrf/utils/queue.py", line 148, in put
    raise Full
```

**Comment by scotthavens** [comment]
In gitlab by @shavens on Jul 11, 2017, 09:51

When you timeout, it doesn't clear the queue but just keeps going. So the thread is trying to put into a full queue which produces an error.

@micahjohnson150 the queue isn't the problem. The underlying IPW image is not correct.

**Comment by scotthavens** [comment]
In gitlab by @micahjohnson150 on Jul 11, 2017, 11:15

I would agree but without threading it runs just fine. If it was an IPW image issue wouldn't I have the same issue without threading? I am now replicating this same issue on the testConfig.ini as well. I am open to leads.

**Comment by scotthavens** [comment]
In gitlab by @shavens on Jul 11, 2017, 11:25

Sorry, getting my issues crossed... this doesn't have to do with the other issue with IPW?

Is the cleaner thread running? It might give you an idea of what is causing the hang up sine it will pause trying to get one of the variables. 

Try to up the timeout as well to ensure that anything that is calculating isn't hanging on something else, then it might give a clue as to what the threads can't get.

**Comment by scotthavens** [comment]
In gitlab by @micahjohnson150 on Jul 11, 2017, 14:59

Ok thousands of print statements I figured out this is because I have added a couple threaded variables in the model framework that aren't always there depending on the nasde model, thus the threads start to hang as they wait for storm_total, and storm_id which are only generated when nasde_model == marks2017.

I have a temporary fix for this in the model_framework I just check for the nasde_model after we initialize the distribution modules. However I don't like that fix and I think it will encourage complicated fixes. I tend to think that we should isolate the modules more by assigning threaded variables from the respective files. Any suggestions?

**Comment by scotthavens** [comment]
In gitlab by @shavens on Jul 11, 2017, 15:03

I'd say that going the route like the `output_variables` in each of the variables. Then during the `__init__` we can set those variables.

**Comment by scotthavens** [comment]
In gitlab by @micahjohnson150 on Jul 11, 2017, 15:07

My thoughts exactly. I will create and issue. Thanks for drudging through this with me.

**Comment by scotthavens** [comment]
In gitlab by @micahjohnson150 on Jul 11, 2017, 15:13

mentioned in issue #17

**Comment by scotthavens** [comment]
In gitlab by @micahjohnson150 on Aug 16, 2017, 15:09

closed
